### ISSUE TITLE
Yii2 Support

### ISSUE THREAD

**Issue by newscloud** [petrabarus/yii.ext.gplacesautocomplete#1]
Hi Petra, I wondered if you would be updating this extension for Yii2? You can email me at jeff@lookahead.io.

Thanks!

**Comment by petrabarus** [comment]
That should be easy to do. Will do it on this weekend. I'll let you know.

**Comment by newscloud** [comment]
Thanks so much Petra. I've actually put in a workaround for now - but it would be great if you update the module.

I'm writing a tutorial for Tuts+ see http://tutsplus.com/authors/jeff-reifman and would be glad to mention you if you update the extension for yii2.

**Comment by petrabarus** [comment]
This is the new plugin for Yii2

https://github.com/petrabarus/yii2-googleplacesautocomplete

**Comment by newscloud** [comment]
You're awesome. Thanks for doing this. I'll include a link in the episode I'm writing right now. It will appear in the next episode of this series: http://code.tutsplus.com/tutorials/building-your-startup-with-php-feature-requirements-and-database-design--cms-22618

Thank you so much!

**Comment by newscloud** [comment]
Petra, are you available for Yii2 / Javascript / JQuery work? I might need some help on a couple of the Meeting Planner components and would be interested in finding someone with skill either to support me with Q&A for hire or writing some code for hire. Email me at jeff@lookahead.io with your rates if you are interested. I don't have anything immediately - but maybe soon.
